In [1]:
import torch
# Set default tensor type to float64
torch.set_default_dtype(torch.float64)

from botorch.test_functions import Ackley

# Test the 5D Ackley function
dim = 5
ackley_function = Ackley(dim=dim)

# Define the objective function
def objective_function(X):
    return ackley_function(2*X-1)

In [14]:
objective_function(init_x)

tensor([3.6027, 3.7801, 4.4003, 3.9919, 3.7410, 3.4719, 3.9597, 3.6775, 2.5159,
        3.4237, 3.7666, 4.5081])

In [2]:
a = torch.rand(1)
a = 0.75 * a + 0.75

b = torch.rand(1)
b = 2.0 * b + 1.0

c = torch.rand(1)
c = 2 * 3.14 * c

In [3]:
a

tensor([0.8040])

In [4]:
b

tensor([2.8660])

In [5]:
c

tensor([2.3003])

In [12]:
pi = 3.14

In [6]:
def cost_function(X):
    X_unnorm = (2.0 * X) - 1.0
    ln_cost_X = a * torch.cos(b * (2 * pi) * (X_unnorm + c)).mean(dim=-1)
    cost_X = torch.exp(ln_cost_X)
    return cost_X

In [15]:
cost_function(init_x)

tensor([0.7738, 1.4625, 1.0699, 0.8604, 1.3715, 1.0754, 0.8887, 1.0347, 0.9509,
        0.9423, 1.2163, 1.5071])

In [7]:
bounds = torch.stack([torch.zeros(dim), torch.ones(dim)])
seed = 42
maximize = False
budget = 5

In [8]:
from pandora_bayesopt.bayesianoptimizer import BayesianOptimizer
from botorch.utils.sampling import draw_sobol_samples
from botorch.acquisition import ExpectedImprovement
from pandora_bayesopt.acquisition.gittins import GittinsIndex

In [9]:
global_optimum_value = 0

In [21]:
torch.manual_seed(seed)
init_x = draw_sobol_samples(bounds=bounds, n=1, q=2*(dim+1)).squeeze(0)

# Example usage with EI
EI_optimizer = BayesianOptimizer(objective=objective_function, dim=dim, maximize=maximize, cost=cost_function, initial_points=init_x, input_standardize=True)
EI_optimizer.run_until_budget(budget=budget, acquisition_function_class=ExpectedImprovement)
EI_best_history = EI_optimizer.get_best_history()
EI_regret_history = EI_optimizer.get_regret_history(global_optimum_value)
EI_cost_history = EI_optimizer.get_cost_history()

Iteration 0, New point: [0.45568794 0.36701297 0.54450917 0.49514284 0.24891346], New value: 2.357226878804362
Best observed value: 2.357226878804362
Current acquisition value: tensor(0.0443)
Cumulative cost: 0.7219854639319656

Iteration 1, New point: [0.42869095 0.41683717 0.57183523 0.50536514 0.31623972], New value: 1.9967739556480244
Best observed value: 1.9967739556480244
Current acquisition value: tensor(0.0364)
Cumulative cost: 1.5628341252055695

Iteration 2, New point: [0.44720008 0.43180234 0.6061904  0.45504654 0.35403349], New value: 1.8668276134808868
Best observed value: 1.8668276134808868
Current acquisition value: tensor(0.0521)
Cumulative cost: 2.378818230501923

Iteration 3, New point: [0.42672213 0.51664283 0.63349761 0.44375008 0.34081903], New value: 2.0782009501122585
Best observed value: 1.8668276134808868
Current acquisition value: tensor(0.0341)
Cumulative cost: 3.3204555522142147

Iteration 4, New point: [0.42259311 0.36996022 0.64881386 0.48035475 0.37372296

In [13]:
from pandora_bayesopt.acquisition.budgeted_multi_step_ei import BudgetedMultiStepLookaheadEI
torch.manual_seed(seed)
init_x = draw_sobol_samples(bounds=bounds, n=1, q=2*(dim+1)).squeeze(0)

# Example usage with BMSEI
BMSEI_optimizer = BayesianOptimizer(objective=objective_function, dim=dim, maximize=maximize, cost=cost_function, initial_points=init_x, input_standardize=True)
BMSEI_optimizer.run_until_budget(budget=budget, acquisition_function_class=BudgetedMultiStepLookaheadEI)
BMSEI_best_history = BMSEI_optimizer.get_best_history()
BMSEI_regret_history = BMSEI_optimizer.get_regret_history(global_optimum_value)
BMSEI_cost_history = BMSEI_optimizer.get_cost_history()

17.770118188374482
Iteration 0, New point: [0.96680011 0.08722208 0.         1.         0.79957692], New value: 4.292819089952438
Best observed value: 2.5158544475683127
Current acquisition value: tensor(0.2926)
Cumulative cost: 0.8003162406665582

18.153528781479935


/Users/qianxie/Desktop/Curriculum/Graduate/Research/PandoraBayesOPT/pandorabayesopt_env/lib/python3.9/site-packages/botorch/models/gpytorch.py:99: BotorchTensorDimensionWarning: Non-strict enforcement of botorch tensor conventions. The following error would have been raised with strict enforcement: Expected X and Y to have the same number of dimensions (got X with dimension 3 and Y with dimension 4).
  warnings.warn(
/Users/qianxie/Desktop/Curriculum/Graduate/Research/PandoraBayesOPT/pandorabayesopt_env/lib/python3.9/site-packages/botorch/models/gpytorch.py:99: BotorchTensorDimensionWarning: Non-strict enforcement of botorch tensor conventions. The following error would have been raised with strict enforcement: Expected X and Y to have the same number of dimensions (got X with dimension 4 and Y with dimension 5).
  warnings.warn(
/Users/qianxie/Desktop/Curriculum/Graduate/Research/PandoraBayesOPT/pandorabayesopt_env/lib/python3.9/site-packages/botorch/models/gpytorch.py:99: BotorchTens

Iteration 1, New point: [0.95682271 1.         0.         0.08190926 0.0553775 ], New value: 3.824477438372338
Best observed value: 2.5158544475683127
Current acquisition value: tensor(0.2976)
Cumulative cost: 1.8776282162753017

18.153528781479935


/Users/qianxie/Desktop/Curriculum/Graduate/Research/PandoraBayesOPT/pandorabayesopt_env/lib/python3.9/site-packages/botorch/models/gpytorch.py:99: BotorchTensorDimensionWarning: Non-strict enforcement of botorch tensor conventions. The following error would have been raised with strict enforcement: Expected X and Y to have the same number of dimensions (got X with dimension 3 and Y with dimension 4).
  warnings.warn(
/Users/qianxie/Desktop/Curriculum/Graduate/Research/PandoraBayesOPT/pandorabayesopt_env/lib/python3.9/site-packages/botorch/models/gpytorch.py:99: BotorchTensorDimensionWarning: Non-strict enforcement of botorch tensor conventions. The following error would have been raised with strict enforcement: Expected X and Y to have the same number of dimensions (got X with dimension 4 and Y with dimension 5).
  warnings.warn(
/Users/qianxie/Desktop/Curriculum/Graduate/Research/PandoraBayesOPT/pandorabayesopt_env/lib/python3.9/site-packages/botorch/models/gpytorch.py:99: BotorchTens

Iteration 2, New point: [0.59283661 0.84247536 0.04949655 0.05919432 0.1535272 ], New value: 4.121686867478726
Best observed value: 2.5158544475683127
Current acquisition value: tensor(0.2879)
Cumulative cost: 3.0336934295830504

18.153528781479935


/Users/qianxie/Desktop/Curriculum/Graduate/Research/PandoraBayesOPT/pandorabayesopt_env/lib/python3.9/site-packages/botorch/models/gpytorch.py:99: BotorchTensorDimensionWarning: Non-strict enforcement of botorch tensor conventions. The following error would have been raised with strict enforcement: Expected X and Y to have the same number of dimensions (got X with dimension 3 and Y with dimension 4).
  warnings.warn(
/Users/qianxie/Desktop/Curriculum/Graduate/Research/PandoraBayesOPT/pandorabayesopt_env/lib/python3.9/site-packages/botorch/models/gpytorch.py:99: BotorchTensorDimensionWarning: Non-strict enforcement of botorch tensor conventions. The following error would have been raised with strict enforcement: Expected X and Y to have the same number of dimensions (got X with dimension 4 and Y with dimension 5).
  warnings.warn(
/Users/qianxie/Desktop/Curriculum/Graduate/Research/PandoraBayesOPT/pandorabayesopt_env/lib/python3.9/site-packages/botorch/models/gpytorch.py:99: BotorchTens

Iteration 3, New point: [0.77529865 0.29786511 0.         0.9598132  0.82744507], New value: 4.559378719206233
Best observed value: 2.5158544475683127
Current acquisition value: tensor(0.1274)
Cumulative cost: 3.835060543391994

18.153528781479935


/Users/qianxie/Desktop/Curriculum/Graduate/Research/PandoraBayesOPT/pandorabayesopt_env/lib/python3.9/site-packages/botorch/models/gpytorch.py:99: BotorchTensorDimensionWarning: Non-strict enforcement of botorch tensor conventions. The following error would have been raised with strict enforcement: Expected X and Y to have the same number of dimensions (got X with dimension 3 and Y with dimension 4).
  warnings.warn(
/Users/qianxie/Desktop/Curriculum/Graduate/Research/PandoraBayesOPT/pandorabayesopt_env/lib/python3.9/site-packages/botorch/models/gpytorch.py:99: BotorchTensorDimensionWarning: Non-strict enforcement of botorch tensor conventions. The following error would have been raised with strict enforcement: Expected X and Y to have the same number of dimensions (got X with dimension 4 and Y with dimension 5).
  warnings.warn(
/Users/qianxie/Desktop/Curriculum/Graduate/Research/PandoraBayesOPT/pandorabayesopt_env/lib/python3.9/site-packages/botorch/models/gpytorch.py:99: BotorchTens

Iteration 4, New point: [0.70468431 0.14059543 0.         1.         0.78555634], New value: 4.580883529375299
Best observed value: 2.5158544475683127
Current acquisition value: tensor(0.0613)
Cumulative cost: 4.575600936406993

18.153528781479935


/Users/qianxie/Desktop/Curriculum/Graduate/Research/PandoraBayesOPT/pandorabayesopt_env/lib/python3.9/site-packages/botorch/models/gpytorch.py:99: BotorchTensorDimensionWarning: Non-strict enforcement of botorch tensor conventions. The following error would have been raised with strict enforcement: Expected X and Y to have the same number of dimensions (got X with dimension 3 and Y with dimension 4).
  warnings.warn(
/Users/qianxie/Desktop/Curriculum/Graduate/Research/PandoraBayesOPT/pandorabayesopt_env/lib/python3.9/site-packages/botorch/models/gpytorch.py:99: BotorchTensorDimensionWarning: Non-strict enforcement of botorch tensor conventions. The following error would have been raised with strict enforcement: Expected X and Y to have the same number of dimensions (got X with dimension 4 and Y with dimension 5).
  warnings.warn(
/Users/qianxie/Desktop/Curriculum/Graduate/Research/PandoraBayesOPT/pandorabayesopt_env/lib/python3.9/site-packages/botorch/models/gpytorch.py:99: BotorchTens

Iteration 5, New point: [0.51761433 0.84148609 0.12629523 0.30540274 0.50408762], New value: 3.39917854158065
Best observed value: 2.5158544475683127
Current acquisition value: tensor(8.0445e-46)
Cumulative cost: 5.099545252697611

